version: '3.3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_container
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    # command: bash -c "npm install && npm run dev"
